### ISSUE TITLE
Any news?

### ISSUE THREAD

**Issue by dumblob** [thebracket/bqos-oss#1]
A very shameless question, but is there any future in this Rust port?

Or was it rather an attempt to see the difference between the Rust approach and the libreqos approach?

Thanks!

**Comment by thebracket** [comment]
It's 100 percent merged into LibreQoS, along with a lot more. 99 percent of
the LibreQoS Rust code is my work!

**Comment by dumblob** [comment]
Wow, thanks a lot for all the hard work and clarification!

I  suppose, this repo can then be archived (perhaps with a message in the repo description and/or `readme.md` that this became part of LibreQoS), right?
